.github/workflows/test-admin-api.yaml
.github/workflows/test-k8s-manager.yaml
.github/workflows/test-mongo-writer.yaml
.github/workflows/test-nats-manager.yaml
engine/admin-api/sonar-project.properties
engine/k8s-manager/sonar-project.properties
engine/mongo-writer/sonar-project.properties
engine/nats-manager/sonar-project.properties

Add CI workflows to this project

Add CI workflows

---

engine/admin-api/.editorconfig

refactor(admin-api): fix editorconfig file selector

---

engine/k8s-manager/Dockerfile
engine/k8s-manager/kubernetes/client.go
engine/k8s-manager/kubernetes/version/manager.go
engine/k8s-manager/kubernetes/version/manager_node.go
engine/k8s-manager/kubernetes/watcher.go

fix(k8s-manager): delete unused code and fix Dockerfile

---

engine/k8s-manager/go.mod
engine/k8s-manager/go.sum

Update go mod and go sum in k8s manager.
Warnings were being reported regarding dependencies in k8s manager.

feat(k8s-manager): update go mod

---

engine/admin-api/delivery/http/controller/graphql.go

fix(admin-api): set user struct to context

---

.github/workflows/test-release.yaml

Fixes a problem when release workflow pushes changes to protected branches
`secre.GITHUB_TOKEN` changed into `secrets.PAT`

ci: fix protected branches permissions

---

.github/workflows/test-release.yaml

ci: fix sonar artifact generation and download

---

scripts/helmfile/values/kai-local/values.yaml.gotmpl

chore: set latest tags for local deployment images

---

.github/workflows/test-release.yaml
helm/kai/CHART.md
helm/kai/values.yaml

Fixes `Test and release` workflow triggers
This solves the issue that provokes that the `Test and release` workflow won't be executed when a PR is created and the origin branch name is not `feat/**` or `fix/**`

ci: fix Test and Release workflow triggers

---

engine/admin-api/adapter/gql/resolver.go
engine/admin-api/domain/usecase/version_interactor.go

Fix error handling to be able to retrieve the error in kli and avoid nil pointer caused by wrong error casting.

fix error handling on version create

---

scripts/kaictl/cmd_build.sh

avoid build deprecated runners

---

README.md

Readme link was outdated and missing requirements
- [ x] Other changes (ci configuration, documentation or any other kind of changes)
- [x ] I have updated the documentation accordingly.

docs: fix outdated link and add missing requirements

---

engine/nats-manager/internal/manager/create_object_store_test.go
engine/nats-manager/internal/manager/nats.go

- Fixed object store name generation
- Replace tags' "." for "_" 
Nats naming doesn't accept "."

Fix(nats-manager): fix object store name generation

---

engine/admin-api/domain/repository/version.go
engine/admin-api/domain/usecase/version/start.go
engine/admin-api/domain/usecase/version/start_test.go
engine/admin-api/mocks/repo_version.go

- Update setStatus parameters in start.go
SetStatus now uses version tag instead of version id, it has to be updated.

fix(admin-api): fix set status search parameters

---

helm/kai/values.yaml

Configure MinIO default pod resources
Default value for memory requests are 16Gi, which is huge amount of memory. We need to reduce it by default

chore(helm): configure minio pods default resources

---

engine/admin-api/adapter/config/viper.go
engine/admin-api/domain/usecase/process_service.go
engine/admin-api/domain/usecase/process_service_test.go
engine/k8s-manager/internal/infrastructure/config/viper.go
engine/k8s-manager/internal/infrastructure/kube/process/create.go
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithCPU.golden
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithEnableGpu.golden
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithMoreReplicas.golden
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden
engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job.golden
helm/kai/templates/engine/admin-api/configmap.yaml
helm/kai/templates/engine/k8s-manager/configmap.yaml

fix: upload and pull image via ingress

---

helm/kai/CHART.md
helm/kai/templates/engine/admin-api/configmap.yaml
helm/kai/templates/engine/admin-api/deployment.yaml
helm/kai/templates/engine/keycloak/ingress.yaml
helm/kai/values.yaml
scripts/helmfile/values/kai-local/values.yaml.gotmpl
scripts/kaictl/cmd_etchost.sh

Pass S3 Credentials and endpoint URL to Admin API pod:
* S3 credentials can be obtained from MinIO if enabled (first option)
* S3 credentials can be obtained from user provided secret (second option)
* S3 Credentials can be obtained from chart values

feat(helm): pass S3 credentials to the API

---

helm/kai/CHART.md
helm/kai/templates/_helpers.tpl
helm/kai/templates/engine/admin-api/configmap.yaml
helm/kai/values.yaml

Set AWS_REGION environement variable into Admin API containers

fix(helm): pass AWS_REGION to Admin API

---

engine/k8s-manager/internal/infrastructure/config/viper.go
engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job.golden
helm/kai/templates/engine/k8s-manager/configmap.yaml

Sets a flag for Kaniko to enable/disable insecure registry config

fix: Kaniko insecure registry flag

---

helm/kai/templates/engine/registry/registry-auth-secret.yaml

fix: make registry protocol configurable

---

engine/admin-api/go.mod
engine/admin-api/go.sum

- Upgrade krt library
Upgrade krt library so triggers don't need to have declared subscriptions.

feat(admin-api): upgrade krt library

---

.nyx.yaml

ci: fix Nyx commit message regex expressions

---

scripts/helmfile/helmfile.yaml

fix(helmfile): refactor helmfile definition to support new versions

---

engine/nats-manager/internal/config/config.go

Fix nats-manager viper configuration alias setting

fix: fix alias setting on nats-manager configuration

---

engine/nats-manager/internal/config/config.go

Fix env variable reading

---

helm/kai/templates/engine/admin-api/minio-config-secret.yaml
scripts/helmfile/values/kai-local/values.yaml.gotmpl

the minio-config secret must not be created when tiering is disabled

fix(helm): minio tier config secret

---

helm/kai/CHART.md
helm/kai/values.yaml
scripts/kaictl/cmd_etchost.sh

feat(helm): enable minio console

---

helm/kai/CHART.md
scripts/helmfile/values/kong/values.yaml

chore: increase kong's proxy buffers size in local env

---

helm/kai/CHART.md
helm/kai/Chart.lock
helm/kai/Chart.yaml
helm/kai/templates/engine/admin-api/configmap.yaml
helm/kai/values.yaml
scripts/kaictl/cmd_etchost.sh

Add Loki and Grafana for KAI management logs
Initially, we needed a Loki to have a log aggregation system for KAI, then we added Grafana since it makes sense to have a place where we can have that logs observability.

feat(helm): add loki-stack to KAI chart

---

engine/admin-api/adapter/repository/mongodb/versionrepository/mapper.go
engine/admin-api/adapter/repository/mongodb/versionrepository/mapper_test.go
engine/admin-api/adapter/service/natsmanager/nats_manager_test.go
engine/admin-api/adapter/service/versionservice/mapper.go
engine/admin-api/adapter/service/versionservice/start_test.go
engine/admin-api/domain/entity/version.go
engine/admin-api/domain/usecase/version/create_test.go
engine/admin-api/domain/usecase/version/krt_mapper.go
engine/admin-api/domain/usecase/version/testdata/classificator_krt.yaml
engine/admin-api/go.mod
engine/admin-api/go.sum
engine/k8s-manager/.golangci.yml
engine/k8s-manager/internal/application/usecase/starter_test.go
engine/k8s-manager/internal/domain/process.go
engine/k8s-manager/internal/infrastructure/grpc/mapper.go
engine/k8s-manager/internal/infrastructure/grpc/version_test.go
engine/k8s-manager/internal/infrastructure/kube/network/create.go
engine/k8s-manager/internal/infrastructure/kube/network/network_test.go
engine/k8s-manager/internal/infrastructure/kube/network/publish_test.go
engine/k8s-manager/internal/infrastructure/kube/network/testdata/CreateNetwork.golden
engine/k8s-manager/internal/infrastructure/kube/network/unpublish_test.go
engine/k8s-manager/internal/infrastructure/kube/process/containers.go
engine/k8s-manager/internal/infrastructure/kube/process/create_test.go
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden
helm/kai/templates/engine/k8s-manager/configmap.yaml

- Added annotations to service creation regarding usage of network protocol
- Protocol inside networking value (process value) is now typed
- Fixed values bug (tls_enabled was bad written)

feature(engine): add protocol annotations to services

---

engine/admin-api/adapter/repository/objectstorage/minio.go

fix(admin-api): enable versioning in generated minio buckets

---

engine/k8s-manager/internal/infrastructure/config/viper.go
engine/k8s-manager/internal/infrastructure/kube/process/containers.go
engine/k8s-manager/internal/infrastructure/kube/process/create_test.go
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithCPU.golden
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithEnableGpu.golden
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithHPA_Deployment.golden
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithMoreReplicas.golden
engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden

fix(k8s-manager): add fluentbit env vars

---

engine/admin-api/adapter/repository/objectstorage/minio.go
engine/admin-api/adapter/repository/objectstorage/testdata/CreateBucketPolicy.golden

fix(admin-api): bucket policy

---

helm/kai/CHART.md
helm/kai/templates/_helpers.tpl
helm/kai/templates/engine/admin-api/configmap.yaml
helm/kai/templates/engine/admin-api/deployment.yaml
helm/kai/templates/engine/redis/redis-secret.yaml
helm/kai/values.yaml

Changes in values.yaml:
make Redis outsourceable by adding the possibility to disable Kai Redis and provide the required parameters to use an external Redis.

feat(helm): make redis optional

---

engine/admin-api/adapter/repository/objectstorage/minio.go
engine/k8s-manager/internal/infrastructure/kube/configuration/testdata/ConfigMapCreation.golden
engine/k8s-manager/internal/infrastructure/kube/configuration/types.go
helm/kai/templates/engine/k8s-manager/deployment.yaml

fix: minio configuration

---

helm/kai/templates/engine/admin-api/configmap.yaml

add Loki variables to admin-api

fix(helm): add loki variables to admin-api

---

scripts/helmfile/helmfile.yaml
scripts/helmfile/values/mongodb-database/values.yaml.gotmpl

feat(helm): update mongo

---

engine/k8s-manager/internal/infrastructure/config/viper.go
engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
engine/k8s-manager/internal/infrastructure/kube/registry/registry_test.go
engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job.golden
helm/kai/CHART.md
helm/kai/templates/engine/k8s-manager/configmap.yaml
helm/kai/values.yaml

fix(k8s-manager): add configurable kaniko image

---

engine/admin-api/adapter/repository/objectstorage/minio.go
engine/admin-api/adapter/repository/objectstorage/minio_test.go
engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job.golden

feat: upload images to .kai subfolder

---

helm/kai/CHART.md
helm/kai/templates/keycloak/deployment.yaml
helm/kai/templates/keycloak/secret.yaml
helm/kai/values.yaml

Keycloak database credentials can be passed via values instead an existing secret

feat(helm): pass keycloak database credentials via values.yaml

---

helm/kai/CHART.md
helm/kai/templates/_helpers.tpl
helm/kai/templates/admin-api/deployment.yaml
helm/kai/templates/grafana/datasources-configmap.yaml
helm/kai/templates/redis/redis-secret.yaml
helm/kai/templates/redis/redis-stack-master-config.yaml
helm/kai/templates/redis/redis-stack-replicas-config.yaml
helm/kai/values.yaml

add redis datasource to grafana

feat(helm): add redis datasource to grafana

---

helm/kai/templates/keycloak/deployment.yaml

fix(helm): keycloak is not being mapped into deployment

---

helm/kai/templates/keycloak/secret.yaml

fix(helm): keycloak db credentials

---

helm/kai/CHART.md
helm/kai/values.yaml

This PR removes the repeated `nodeSelectors`, `affinities` and `tolerations` objects inside the nats values definition.

fix(helm): remove repeated values for nats

---

engine/k8s-manager/internal/infrastructure/config/viper.go
engine/k8s-manager/internal/infrastructure/kube/network/publish.go
engine/k8s-manager/internal/infrastructure/kube/network/publish_test.go
engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_GRPCTrigger.golden

fix(k8s-manager): get tls secret name from env vars

---

helm/kai/CHART.md
helm/kai/templates/_helpers.tpl
helm/kai/values.yaml

fix(helm): Redis default URLs

---

engine/admin-api/domain/service/auth/errors_test.go
engine/nats-manager/internal/manager/update_configuration_test.go

fix: missing tags

---

helm/kai/templates/nats-manager/deployment.yaml

Fix imagePullSecrets parameter in Nats Manager deployment

fix: Nats Manager imagePullSecrets

---

engine/k8s-manager/internal/infrastructure/config/viper.go
helm/kai/CHART.md
helm/kai/templates/k8s-manager/configmap.yaml
helm/kai/values.yaml

fix(k8s-manager): make log level configurable and set default to info

---

README.md

fix: wrong links

---

helm/kai/templates/admin-api/deployment.yaml
helm/kai/templates/k8s-manager/deployment.yaml
helm/kai/templates/keycloak/deployment.yaml
helm/kai/templates/nats-manager/deployment.yaml
helm/kai/templates/registry/deployment.yaml
helm/kai/values.yaml

Allow set a strategy for adminApi, keycloak, k8sManager and natsManager deployments.
Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy

feat(helm): allow set deployment strategies

---

engine/admin-api/domain/usecase/process/register.go
engine/admin-api/domain/usecase/process/register_test.go

fix: product register check if product exists
